### ISSUE TITLE
Absorb DerelictCF

### ISSUE THREAD

**Issue by p0nce** [p0nce/DerelictCarbon#3]
https://github.com/Extrawurst/DerelictCF

**Comment by p0nce** [comment]
@Extrawurst merged derelict-cf into derelict-carbon starting with tag v1.1.0
It is untested.

```
DerelictCoreFoundation.load(); // to load CF functions
```

Untested yet. Minimum supported OS X version should be 10.7 or maybe lower.
Let me know if something goes unwell.

**Comment by extrawurst** [comment]
Great thank you! I will give it a spin

**Comment by extrawurst** [comment]
Looks great! Thanks! The only project using those methods still works :)
